name: Update README with dev.to posts

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest dev.to posts
        run: |
          curl https://dev.to/api/articles?username=anikakash > devto.json
      - name: Update README.md
        run: |
          python3 update_readme.py
      - name: Commit changes
        run: |
          git config --global user.name "your-github-username"
          git config --global user.email "your-email"
          git add README.md
          git commit -m "Update dev.to posts"
          git push
