name: Update README with dev.to posts

on:
  schedule:
    - cron: "0 20 * * *"  # Change this to run after 2 AM in Bangladesh time (20:00 UTC is 2 AM BD time)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required Python packages
      run: |
        pip install requests

    - name: Update README with latest dev.to posts
      run: |
        python .github/workflows/update_readme.py

    - name: Pull latest changes
      run: git pull origin main --rebase

    - name: Push changes
      run: |
        git config --global user.name "anikakash"
        git config --global user.email "anik15-14210@diu.edu.bd"
        git add README.md
        git commit -m "Update dev.to posts"
        git push origin main
