name: Update README with dev.to posts

on:
  schedule:
    # Run at 8:15 PM UTC (2:15 AM Bangladesh time) every day
    - cron: "0 7 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Ensure Python dependencies are installed
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      # Fetch the latest dev.to posts and update the README
      - name: Get latest dev.to posts and update README
        run: |
          python3 .github/workflows/update_readme.py

      # Commit changes to the repository
      - name: Commit changes
        run: |
          git config --global user.name "anikakash"
          git config --global user.email "anik15-14210@diu.edu.bd"
          git add README.md
          git commit -m "Update dev.to posts"
          git push
